blank_issues_enabled: false
contact_links:
  - name: Guild.xyz Support
    url: https://guild.xyz
    about: For direct support, please visit our site and click on the small Intercom icon in the bottom right corner.
